name: build
on:
  release:
    types: [created]
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Linux
          - GOOS: linux
            GOARCH: amd64
          - GOOS: linux
            GOARCH: arm
          - GOOS: linux
            GOARCH: arm64
          - GOOS: linux
            GOARCH: mips
            ENV: GOMIPS=softfloat
          - GOOS: linux
            GOARCH: mipsle
            ENV: GOMIPS=softfloat
          - GOOS: linux
            GOARCH: mips64
            ENV: GOMIPS=softfloat
          - GOOS: linux
            GOARCH: mips64le
            ENV: GOMIPS=softfloat
          - GOOS: linux
            GOARCH: riscv64

          # Windows
          - GOOS: windows
            GOARCH: amd64
            ext: .exe
          - GOOS: windows
            GOARCH: arm64
            ext: .exe

          # macOS
          - GOOS: darwin
            GOARCH: amd64
          - GOOS: darwin
            GOARCH: arm64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'
          check-latest: true

      - name: Prepare Build Environment
        run: mkdir -p dist

      - name: Build Binary
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
          APP_NAME: Esurfing-go
          EXT: ${{ matrix.ext || '' }}
        run: |
          if [ -n "${{ matrix.ENV }}" ]; then
            export ${{ matrix.ENV }}
          fi
          OUTPUT="dist/${APP_NAME}-${GOOS}-${GOARCH}${EXT}"
          go build -trimpath -ldflags="-s -w" -o "$OUTPUT" .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Esurfing-go-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.ext || '' }}
          path: dist/

  release:
    name: Create Release
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate Checksums
        run: |
          cd dist
          sha256sum */* > SHA256SUMS.txt

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            dist/*
            dist/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}